repos:
  - repo: local
    hooks:
      - id: makeFix
        name: Run Makefile lint
        entry: make lint
        language: system
        pass_filenames: false
      - id: makeFmt
        name: Run Makefile format
        entry: make format
        language: system
        pass_filenames: false
