repos:
  -   repo: local
      hooks:
        -   id: make
            name: Run Makefile
            entry: make format lint
            language: system
            pass_filenames: false
            types: [shell]